# Generated by Django 3.2.4 on 2021-06-26 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'bulbasaur'), ('2', 'ivysaur'), ('3', 'venusaur'), ('4', 'charmander'), ('5', 'charmeleon'), ('6', 'charizard'), ('7', 'squirtle'), ('8', 'wartortle'), ('9', 'blastoise'), ('10', 'caterpie'), ('11', 'metapod'), ('12', 'butterfree')], default='1', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
