# Generated by Django 3.2.4 on 2021-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210626_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonslist',
            name='semester',
        ),
        migrations.AddField(
            model_name='pokemonslist',
            name='name_pokemon',
            field=models.CharField(choices=[('1', 'bulbasaur'), ('2', 'ivysaur'), ('3', 'venusaur'), ('4', 'charmander'), ('5', 'charmeleon'), ('6', 'charizard'), ('7', 'squirtle'), ('8', 'wartortle'), ('9', 'blastoise'), ('10', 'caterpie'), ('11', 'metapod'), ('12', 'butterfree'), ('13', 'weedle'), ('14', 'kakuna'), ('15', 'beedrill'), ('16', 'pidgey'), ('17', 'pidgeotto'), ('18', 'pidgeot'), ('19', 'rattata'), ('20', 'raticate'), ('21', 'spearow'), ('22', 'fearow'), ('23', 'ekans')], default='1', max_length=20),
        ),
    ]
