# Generated by Django 3.2.4 on 2021-06-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_pokemonslist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonslist',
            old_name='user',
            new_name='user1',
        ),
    ]
