# Generated by Django 3.2.4 on 2021-06-27 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210627_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonslist',
            name='author',
            field=models.CharField(max_length=120, null=True, verbose_name=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
