# Generated by Django 3.2.4 on 2021-06-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_pokemonslist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonslist',
            name='author',
        ),
    ]
