# Generated by Django 3.2.4 on 2021-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_pokemonslist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonslist',
            name='name_pokemon',
            field=models.CharField(choices=[('bulbasaur', 'bulbasaur'), ('ivysaur', 'ivysaur'), ('venusaur', 'venusaur'), ('charmander', 'charmander'), ('charmeleon', 'charmeleon'), ('charizard', 'charizard'), ('squirtle', 'squirtle'), ('wartortle', 'wartortle'), ('blastoise', 'blastoise'), ('caterpie', 'caterpie'), ('metapod', 'metapod'), ('butterfree', 'butterfree'), ('weedle', 'weedle'), ('kakuna', 'kakuna'), ('beedrill', 'beedrill'), ('pidgey', 'pidgey'), ('pidgeotto', 'pidgeotto'), ('pidgeot', 'pidgeot'), ('rattata', 'rattata'), ('raticate', 'raticate'), ('spearow', 'spearow'), ('fearow', 'fearow'), ('ekans', 'ekans')], default='1', max_length=20),
        ),
    ]
